### PR TITLE
remove gulp directory, which is legacy and makes the prod build fail

### PR DESCRIPTION
**Pull request by jdubois**
Ping @pascalgrimaud this directory should have been removed a long time ago

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Ahaha Indeed !!!

**Comment by jdubois** [comment]
And now my "secret" project works perfectly with all JHipster samples 👍

**Comment by pascalgrimaud** [comment]
@jdubois : with Cassandra sample too ?!

**Comment by jdubois** [comment]
No, not with Cassandra. It would be very easy to do, but I'm trying to play nice with DataStax!

**Pull request merged**
